Fix polarssl url as polarssl.org no longer exists
ps3dev/ps3libraries pull request #58
Opened 2022-07-01 15:23 UTC by fengye

It looks like polarssl.org no longer exists so I managed to find the package in src.fedoraproject.org so that the build can work

2022-07-03 14:00 UTC, zeldin commented
Thanks.
I think it would make more sense to fetch it from `tls.mbed.org` like it is done on the `develop` branch though.
Could you plese test if using `https://tls.mbed.org/download/polarssl-${VERSION}-gpl.tgz` as the URI instead works for you?

2022-07-03 17:29 UTC, fengye commented
Hi @zeldin , it looks like I can't access https://tls.mbed.org/download/polarssl-1.2.8-gpl.tgz which version is stated in the script. On `develop` branch the url https://tls.mbed.org/download/polarssl-1.3.9-gpl.tgz is inaccessible neither.

2022-07-03 17:53 UTC, zeldin commented
😞 Looks like `tls.mbed.org` is also out of commission.  It redirects to `www.trustedfirmware.org`, which doesn't seem to host any software packages at all (what I can find), but just refers to github...  What a mess.

2022-07-05 00:23 UTC, miigotu requested changes
The version variable needs to be used in both the downloaded file name and the URL.

2022-07-06 01:32 UTC, miigotu commented
Any chance we can update this to a recent release of polarssl so we can use their GitHub release zips? 

In any event, we can download a zip or tarball of the 1.2.8 tagged release on their GitHub 

https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/polarssl-1.2.8.zip

https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/polarssl-1.2.8.tar

We can also get a tarball, and also use the ${version} tag correctly. If we switch to this method, all we need to do is update the patch and version tag for a newer release and stay cleanly within this project's scripts preferred methods.

2022-07-06 02:50 UTC, miigotu commented
I think this should be expanded to a proper update and full test by @ps3dev/developers because we are super behind on libcurl and polarssl ->mbedtls, which is a security concern depending on what an end user does with the libraries we provide. I am almost sure most of us developers find it pertinent to remove sticks from the paths of less security focused and/or less experienced developers by not building insecure versions of curl and ssl libraries for extended periods of time. Leaving the older versions as an option for BC I can understand, 
for when older software just will not build with updated versions (that those downstream applications should also just be updated is another discussion, let's control what we can) but as the default I am feeling a sense of responsibility. 

As this is a substantial change, I think I will convert this comment to an issue so we can discuss and maybe I'll create a PR/branch and just start working on it. This is going to go fairly deep with dependency, because practically everything uses libcurl or ssl in some way these days lol.

2022-07-23 21:32 UTC, gtessi commented
Hello,

I was getting into develop my first homebrew app for the PS3 and got into this issue. I can confirm that the fix works perfect and allowed me to continue compiling the tools.

But the main repo with the path pointing to polarssl.org will timeout and retry forever I believe (got 11 retries before I stopped the script).

2022-08-05 16:29 UTC, zeldin commented
As a stop-gap measure I pushed a version which fetches from github and actually works (sorry miigoto) :smile:

2022-08-05 17:20 UTC, gtessi commented
I want to add that my fork compiles correctly with some additional changes needed: https://github.com/gtessi/ps3libraries

2022-08-05 19:58 UTC, miigotu commented
No problem, I'm in no rush haha

2024-03-03 00:19 UTC, humbertodias commented
polarssl 1.3.9 added here https://github.com/ps3dev/ps3libraries/pull/64

2026-06-06 21:44 UTC, bucanero commented
Closing this PR since 337bb8a9d78dc8e55afd4c1c909fd46a91baed59 updated the library version and link (polarssl-1.3.9)

2026-06-06 21:44 UTC, closed without merging